language: objective-c
before_install:
  - brew update
  - brew install leveldb

script: "bash build.sh && cd test && python test.py"
branches:
  only:
    - master
notifications:
  email:
    - andrew@andrewschaaf.com
